apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-dhcp-kea-jobs
data:
  dhcp-helper.py: |-
{{ .Files.Get "files/dhcp-helper.py" | indent 4 }}
  cray-dhcp-kea-dhcp4.conf.template: |-
{{ .Files.Get "files/cray-dhcp-kea-dhcp4.conf" | indent 4 }}
