apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-dhcp-kea-backup-v2
binaryData:
  {{- $configmap := (lookup "v1" "ConfigMap" .Release.Namespace "cray-dhcp-kea-backup-v2") }}
  {{- if $configmap }}
  {{- $config := get $configmap.binaryData "keaBackup.conf.gz" }}
  keaBackup.conf.gz: {{ $config }}
  {{- else }}
  keaBackup.conf.gz: {{ .Values.keaBackupGzip }}
  {{- end }}
