apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-dhcp-kea-dhcp4-conf
  namespace: services
data:
  cray-dhcp-kea-dhcp4.conf: |-
    {
      "Dhcp4": {{ toPrettyJson .Values.crayDhcpKeaDhcp4Config.dhcp4 | indent 4 }}
    }
