apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-dhcp-kea-ctrl-agent-conf
  namespace: services
data:
  cray-dhcp-kea-ctrl-agent.conf: |-
{{ toPrettyJson .Values.crayDhcpKeaCtrlAgentConfig | indent 4 }}