---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "cray-dhcp-kea-service"
  labels:
    app.kubernetes.io/name: cray-dhcp-kea
spec:
  host: "cray-dhcp-kea"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
