---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-dhcp-kea-init
  labels:
    app: cray-dhcp-kea-init
spec:
  template:
    metadata:
      labels:
        app: cray-dhcp-kea-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "jobs-watcher"
      containers:
        - name: cray-dhcp-kea-init
          image: {{ include "cray-dhcp-kea.image-prefix" .Values }}cray/cray-dhcp-kea:latest
          command:
            - "/bin/sh"
            - "-c"
            - "PGPASSWORD=$DHCP_DBPASS /usr/bin/psql -h $DHCP_DBHOST -U $DHCP_DBUSER -d $DHCP_DBNAME -a -f dhcpdb_create.sql"
          env:
          - name: DHCP_DBHOST
            value: cray-dhcp-kea-postgres
          - name: DHCP_DBPORT
            value: "5432"
          - name: DHCP_DBNAME
            value: "dhcp"
          - name: DHCP_DBOPTS
            value: ""
          - name: DHCP_DBUSER
            valueFrom:
              secretKeyRef:
                name: dhcpdsuser.cray-dhcp-kea-postgres.credentials
                key: username
          - name: DHCP_DBPASS
            valueFrom:
              secretKeyRef:
                name: dhcpdsuser.cray-dhcp-kea-postgres.credentials
                key: password 
          - name: DHCP_DBOPTS
            value: ""
          volumeMounts:
            - name: cray-dhcp-kea-db-init
              mountPath: /dhcpdb_create.sql
              readOnly: false
              subPath: cray-dhcp-kea-dhcp4.conf
      initContainers:
        - name: "wait-for-postgres-job-watcher"
          image: {{ include "cray-dhcp-kea.image-prefix" .Values }}loftsman/docker-kubectl:latest
          command:
            - /bin/sh
            - -c
            - while [ "`kubectl get jobs -n services cray-dhcp-kea-wait-for-postgres -o jsonpath='{.status.conditions[0].type}'`" != "Complete" ]; do echo "Waiting for cray-dhcp-kea-wait-for-postgres to complete"; sleep 3 ; done; echo "Completed";
