---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cray-dhcp-kea-helper
spec:
  {{ with .Values.jobs.helper.schedule -}}
    schedule: "{{.minute}} {{.hour}} {{.dayOfMonth}} {{.month}} {{.dayOfWeek}}"
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: helper
              image: {{ include "cray-dhcp-kea.image-prefix" .Values }}cray/cray-dhcp-kea:latest
              command: ["/bin/dhcp-helper.py"]
              resources:
                requests:
                  memory: "160Mi"
                  cpu: "500m"
                limits:
                  memory: "320Mi"
                  cpu: "1500m"
              volumeMounts:
                - name: cray-dhcp-kea-jobs
                  mountPath: /bin/dhcp-helper.py
                  readOnly: true
                  subPath: dhcp-helper.py
                - name: cray-dhcp-kea-jobs-template
                  mountPath: /bin/cray-dhcp-kea-dhcp4.conf
                  readOnly: true
                  subPath: cray-dhcp-kea-dhcp4.conf
          volumes:
            - name: cray-dhcp-kea-jobs
              configMap:
                defaultMode: 0700
                name: cray-dhcp-kea-jobs
            - name: cray-dhcp-kea-jobs-template
              configMap:
                defaultMode: 0700
                name: cray-dhcp-kea-jobs-template