---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-dhcp-kea-init-{{ .Release.Revision }}
  labels:
    app: cray-dhcp-kea-init
spec:
  template:
    metadata:
      labels:
        app: cray-dhcp-kea-init
    spec:
      restartPolicy: OnFailure
      backoffLimit: {{ .Values.initJobBackoffLimit }}
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        runAsNonRoot: true
      serviceAccountName: cray-dhcp-kea
      containers:
        - name: cray-dhcp-kea-init
          image: {{ .Values.image.repository }}:{{ .Values.global.appVersion }}
          command: ["/srv/kea/startup-init.sh"]
          env:
            {{- index .Values "cray-service" "containers" "cray-dhcp-kea" "env" | toYaml | nindent 12 }}
          volumeMounts:
            - name: cray-dhcp-kea-jobs
              mountPath: /srv/kea
            - name: cray-ipxe-settings
              mountPath: /srv/ipxe
            - name: cray-dhcp-kea-backup-v2
              mountPath: /srv/kea/backup
          securityContext:
            runAsUser: 100
            runAsGroup: 101
            runAsNonRoot: true
      volumes:
        - name: cray-dhcp-kea-jobs
          configMap:
            defaultMode: 0777
            name: cray-dhcp-kea-jobs
        - name: cray-ipxe-settings
          configMap:
            name: cray-ipxe-settings
            optional: true
        - name: cray-dhcp-kea-backup-v2
          configMap:
            name: cray-dhcp-kea-backup-v2
            defaultMode: 0777
            optional: true
