---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-dhcp-kea-init
  labels:
    app: cray-dhcp-kea-init
spec:
  template:
    metadata:
      labels:
        app: cray-dhcp-kea-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "jobs-watcher"
      containers:
        - name: cray-dhcp-kea-init
          image: {{ include "cray-dhcp-kea.image-prefix" .Values }}cray/cray-dhcp-kea:latest
          command:
            - "/bin/sh"
            - "-c"
            - "PGPASSWORD=$DHCP_DBPASS /usr/bin/psql -h $DHCP_DBHOST -U $DHCP_DBUSER -d $DHCP_DBNAME -a -f dhcpdb_create.sql"
          env:
          - name: DHCP_DBHOST
            value: cray-dhcp-kea-postgres
          - name: DHCP_DBPORT
            value: "5432"
          - name: DHCP_DBNAME
            value: "dhcp"
          - name: DHCP_DBOPTS
            value: ""
          - name: DHCP_DBUSER
            valueFrom:
              secretKeyRef:
                name: dhcpdsuser.cray-dhcp-kea-postgres.credentials
                key: username
          - name: DHCP_DBPASS
            valueFrom:
              secretKeyRef:
                name: dhcpdsuser.cray-dhcp-kea-postgres.credentials
                key: password
          - name: DHCP_DBOPTS
            value: ""
          volumeMounts:
            - name: cray-dhcp-kea-db-init
              mountPath: /dhcpdb_create.sql
              readOnly: false
              subPath: dhcpdb_create.sql
      volumes:
        - name: cray-dhcp-kea-db-init
          configMap:
            name: cray-dhcp-kea-db-init
      initContainers:
        - name: "wait-for-postgres-job-watcher"
          image: {{ include "cray-dhcp-kea.image-prefix" .Values }}loftsman/docker-kubectl:latest
          command:
            - /bin/sh
            - -c
            - while [ "`kubectl get jobs -n services cray-dhcp-kea-wait-for-postgres -o jsonpath='{.status.conditions[0].type}'`" != "Complete" ]; do echo "Waiting for cray-dhcp-kea-wait-for-postgres to complete"; sleep 3 ; done; echo "Completed";
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cray-dhcp-kea-helper
spec:
  {{ with .Values.jobs.helper.schedule -}}
    schedule: "{{.minute}} {{.hour}} {{.dayOfMonth}} {{.month}} {{.dayOfWeek}}"
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: helper
              image: {{ include "cray-dhcp-kea.image-prefix" .Values }}cray/cray-dhcp-kea:latest
              command: ["/bin/dhcp-helper.py"]
              resources:
                requests:
                  memory: "160Mi"
                  cpu: "500m"
                limits:
                  memory: "320Mi"
                  cpu: "1500m"
              volumeMounts:
                - name: cray-dhcp-kea-jobs
                  mountPath: /bin/dhcp-helper.py
                  readOnly: true
                  subPath: dhcp-helper.py
          volumes:
            - name: cray-dhcp-kea-jobs
              configMap:
                defaultMode: 0700
                name: cray-dhcp-kea-jobs
