---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-back
  labels:
    {{- include "cray-dhcp-kea.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-back-role-binding
  labels:
    {{- include "cray-dhcp-kea.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "cray-dhcp-kea.fullname" . }}-back
  namespace: {{ .Release.Namespace }}