---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
  labels:
    {{- include "cray-dhcp-kea.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup-role-binding
  labels:
    {{- include "cray-dhcp-kea.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "cray-dhcp-kea.fullname" . }}-backup
    namespace: services
