apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "cray-dhcp-kea.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - patch
  resourceNames:
  - cray-dhcp-kea-backup-v2
- apiGroups: ["", "batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted-transition-net-raw
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "cray-dhcp-kea.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cray-dhcp-kea.fullname" . }}-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "cray-dhcp-kea.fullname" . }}
    namespace: services
