---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-ingress-tcp
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/address-pool: node-management
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  ports:
    - name: kea-server-tcp
      port: 67
      protocol: TCP
      targetPort: 67
    - name: kea-client-tcp
      port: 68
      protocol: TCP
      targetPort: 68
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-ingress-udp
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/address-pool: node-management
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  ports:
    - name: kea-server-udp
      port: 67
      protocol: UDP
      targetPort: 67
    - name: kea-client-udp
      port: 68
      protocol: UDP
      targetPort: 68
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-ctrl-socket-ingress-tcp
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/address-pool: node-management
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  ports:
    - name: kea-ctrl-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
