---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-tcp-hmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/allow-shared-ip:  cray-dhcp-kea-hmn
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.hmnLoadBalancerIp }}
  externalTrafficPolicy: Local
  ports:
    - name: kea-server-tcp-hmn
      port: 67
      protocol: TCP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-tcp-nmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip:  cray-dhcp-kea-nmn
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.nmnLoadBalancerIp }}
  externalTrafficPolicy: Local
  ports:
    - name: kea-server-tcp-nmn
      port: 67
      protocol: TCP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-udp-hmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/allow-shared-ip:  cray-dhcp-kea-hmn
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.hmnLoadBalancerIp }}
  externalTrafficPolicy: Local
  ports:
    - name: kea-server-udp-hmn
      port: 67
      protocol: UDP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-udp-nmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip:  cray-dhcp-kea-nmn
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.nmnLoadBalancerIp }}
  externalTrafficPolicy: Local
  ports:
    - name: kea-server-udp-nmn
      port: 67
      protocol: UDP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dhcp-kea-api
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip:  cray-dhcp-kea-nmn
    external-dns.alpha.kubernetes.io/hostname: cray-dhcp-kea
spec:
  type: ClusterIP
  ports:
    - name: kea-api
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: cray-dhcp-kea
