# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  type: Deployment
  nameOverride: cray-dhcp
  containers:
    - name: cray-dhcp
      image:
        repository: cray-dhcp
        pullPolicy: Always
      env:
        - name: DHCP_DBHOST
          value: cray-dhcp-postgres
        - name: DHCP_DBPORT
          value: "5432"
        - name: DHCP_DBNAME
          value: "dhcp"
        - name: DHCP_DBOPTS
          value: ""
        - name: DHCP_DBUSER
          valueFrom:
            secretKeyRef:
              name: dhcpdsuser.cray-dhcp-postgres.credentials
              key: username
        - name: DHCP_DBPASS
          valueFrom:
            secretKeyRef:
              name: dhcpdsuser.cray-dhcp-postgres.credentials
              key: password            
      ports:
        - name: dhcp-server-udp
          containerPort: 67
          protocol: UDP
        - name: dhcp-server-tcp
          containerPort: 67
          protocol: TCP
        - name: dhcp-client-udp
          containerPort: 68
          protocol: UDP
        - name: dhcp-client-tcp
          containerPort: 68
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 67
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        tcpSocket:
          port: 67
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: cray-dhcp-kea-dhcp4-conf
          mountPath: /kea-dhcp4.conf
          readOnly: false
          subPath: kea-dhcp4.conf
  volumes:
    - name: cray-dhcp-kea-dhcp4-conf
      configMap:
        name: cray-dhcp-kea-dhcp4-conf
  sqlCluster:
    enabled: true
    users:
      dhcpdsuser: []
    databases:
      dhcp: dhcpdsuser
    volumeSize: 10Gi
  ingress:
    enabled: true
keaConfig:
  dhcp4:
    interfaces-config:
      interfaces:
      - "*"
      dhcp-socket-type: raw
    lease-database:
      type: postgresql
      name: "$DHCP_DBNAME"
      host: "$DHCP_DBHOST"
      user: "$DHCP_DBUSER"
      password: "$DHCP_DBPASS"
    valid-lifetime: 4000
    subnet4:
    - subnet: 192.168.10.0/24
      pools:
      - pool: 192.168.10.10 - 192.168.10.100
      option-data:
      - name: routers
        data: 192.168.10.1
      - name: domain-name-servers
        data: 1.1.1.1
  Logging:
    loggers:
    - name: kea-dhcp4
      output_options:
      - output: stdout
      severity: DEBUG
    
