version: '3'

services:
  cray-dhcp-kea-api:
    build: .
    image: cray-dhcp-kea-api:latest
    container_name: cray-dhcp-kea-api
#    privileged: true
    dns:
      - 10.92.100.225
    extra_hosts:
      - "api-gw-service-nmn.local:10.92.100.71"
    volumes:
      - cray-dhcp-kea-socket:/cray-dhcp-kea-socket
      - /root/.kube_kea:/home/kea/.kube
    network_mode: host
    environment:
    ports:
          - 67:6067/udp
          - 67:6067/tcp
#          - 68:6068/udp
#          - 68:6068/tcp
          - 8000:8000
    environment:
      DHCP_CAHOST: 0.0.0.0 # KEA Control agent host
      DHCP_CAPORT: 8000 # KEA Control agent port
    restart: always
    entrypoint: "/srv/kea/external_startup.sh"
volumes:
  cray-dhcp-kea-socket: