version: '3'

services:
  kea:
    #build: .
    image: cray-dhcp-kea:latest
    container_name: kea
    volumes:
      - ./kea-dhcp4.conf:/kea-dhcp4.conf
    network_mode: host
    environment:
      DHCP_DBHOST: 127.0.0.1
      DHCP_DBUSER: postgres
      DHCP_DBNAME: dhcpdb
      DHCP_DBPASS: dhcpdb
    #    ports:
    #      - 67:67/udp
    #      - 67:67/tcp
    #      - 68:68/udp
    #      - 68:68/tcp
    depends_on:
      - kea-db
    restart: always
    #    entrypoint: "tail -f"
  kea-db:
    image: postgres
    container_name: kea-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dhcpdb
      POSTGRES_PASSWORD: dhcpdb
    restart: always
