version: '3'

services:
  cray-dhcp-kea:
    build: .
    image: cray-dhcp-kea:latest
    container_name: cray-dhcp-kea
    volumes:
      - cray-dhcp-kea-socket:/cray-dhcp-kea-socket
#    network_mode: host
    environment:
    ports:
          - 67:6067/udp
          - 67:6067/tcp
#          - 68:6068/udp
#          - 68:6068/tcp
    environment:
      DHCP_CAHOST: 127.0.0.1 # KEA Control agent host
      DHCP_CAPORT: 8000 # KEA Control agent port
    restart: always
    entrypoint: "/srv/kea/external_startup_dhcp.sh"
  cray-dhcp-kea-ctrl-agent:
    image: cray-dhcp-kea:latest
    container_name: cray-dhcp-api
    privileged: true
    volumes:
      - cray-dhcp-kea-socket:/cray-dhcp-kea-socket
    ports:
      - 8000:8000
    restart: always
    entrypoint: "/srv/kea/external_startup_dhcp_ctrl_agent.sh"
    environment:
      DHCP_CAHOST: 0.0.0.0 # KEA Control agent host
      DHCP_CAPORT: 8000 # KEA Control agent port
    depends_on:
      - cray-dhcp-kea
volumes:
  cray-dhcp-kea-socket:
