# Copyright 2023 Hewlett Packard Enterprise Development LP
apiVersion: v2
name: cray-dhcp-kea
version: 0.11.5

description: Kubernetes resources for cray-dhcp-kea
home: https://github.com/Cray-HPE/cray-dhcp-kea
dependencies:
  - name: cray-service
    version: "~11.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-postgresql
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: dle-hpe
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
  - name: Management Network
    url: https://github.com/orgs/Cray-HPE/teams/management-network
appVersion: 0.11.5
annotations:
  artifacthub.io/images: |
    - name: cray-dhcp-kea
      image: artifactory.algol60.net/csm-docker/stable/cray-dhcp-kea:0.11.5
  artifacthub.io/license: MIT
