#
# Copyright 2020, 2021 Hewlett Packard Enterprise Development LP
#
apiVersion: v1
description: "Kubernetes resources for cray-dhcp-kea"
name: "cray-dhcp-kea"
home: "cloud/cray-dhcp-kea"
version: 0.9.8
