# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
nmnLoadBalancerIp: 10.92.100.222
hmnLoadBalancerIp: 10.94.100.222
  containers:
    cray-service:
      type: Deployment
      nameOverride: cray-dhcp-kea
      podAnnotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "67"
        cray-dhcp-kea:
          name: "cray-dhcp-kea"
          image:
            repository: "cray/cray-dhcp-kea"
          command:
            - "sh"
            - "-c"
            - "/startup-dhcp.sh"
          resources:
            limits:
              cpu: "6"
              memory: "3Gi"
            requests:
              cpu: "2"
              memory: "1Gi"
          env:
            - name: DNS_MASQ_HOSTNAME
              value: "ncn-w001"
            - name: TFTP_SERVER_NMN
              value: "10.92.100.60"
            - name: TFTP_SERVER_HMN
              value: "10.94.100.60"
            - name: UNBOUND_SERVER_NMN
              value: "10.92.100.225"
            - name: UNBOUND_SERVER_HMN
              value: "10.94.100.225"
            - name: NMN_LOADBALANCER_IP
              value: "10.92.100.222"
            - name: HMN_LOADBALANCER_IP
              value: "10.94.100.222"
            - name: DHCP_HELPER_DEBUG
              value: "false"
            - name: DHCP_HELPER_INTERVAL_SECONDS
              value: "180"
            - name: KEA_SOCKET
              value: "/cray-dhcp-kea-socket/cray-dhcp-kea.socket"
            - name: KEA_EXPORTER_ADDRESS
              value: "0.0.0.0"
            - name: KEA_EXPORTER_PORT
              value: "8080"
          ports:
            - name: kea-server-udp
              containerPort: 67
              protocol: UDP
            - name: kea-server-tcp
              containerPort: 67
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /health-check.sh
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 67
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: cray-dhcp-kea-socket
              mountPath: /cray-dhcp-kea-socket
              readOnly: false
              subPath: cray-dhcp-kea-socket
            - name: cray-dhcp-kea-jobs
              mountPath: /dhcp-helper.py
              readOnly: true
              subPath: dhcp-helper.py
            - name: cray-dhcp-kea-jobs
              mountPath: /cray-dhcp-kea-dhcp4.conf.template
              readOnly: true
              subPath: cray-dhcp-kea-dhcp4.conf.template
            - name: cray-dhcp-kea-jobs
              mountPath: /health-check.sh
              readOnly: true
              subPath: health-check.sh
        enabled: false
crayDhcpKeaCtrlAgentConfig:
  Control-agent:
    control-sockets:
      dhcp4:
        socket-name: /cray-dhcp-kea-socket/cray-dhcp-kea.socket
        socket-type: unix
    http-host: 0.0.0.0
    http-port: 8000
    loggers:
      - name: cray-dhcp-kea-ctrl-agent
        output_options:
          - output: stdout
        severity: ERROR
